#!/bin/bash

root -l -b -q fpPb_Incl_Kshort.C
root -l -b -q fpPb_Incl_Kshort_Cent.C
root -l -b -q fpPb_Incl_Lambda.C
root -l -b -q fpPb_Incl_Lambda_Cent.C
root -l -b -q fpPb_Incl_LKRatio.C
root -l -b -q fpPb_Incl_LKRatio_Cent.C
root -l -b -q fpPb_Incl_OKRatio.C
root -l -b -q fpPb_Incl_OLRatio.C
root -l -b -q fpPb_Incl_Omega.C
root -l -b -q fpPb_Incl_OXRatio.C
root -l -b -q fpPb_Incl_Xi.C
root -l -b -q fpPb_Incl_Xi_Cent.C
root -l -b -q fpPb_Incl_XKRatio.C
root -l -b -q fpPb_Incl_XKRatio_Cent.C
root -l -b -q fpPb_Incl_XLRatio.C
root -l -b -q fpPb_Incl_XLRatio_Cent.C
root -l -b -q fpPb_JE_Kshort.C
root -l -b -q fpPb_JE_Kshort_Cent.C
root -l -b -q fpPb_JE_Lambda.C
root -l -b -q fpPb_JE_Lambda_Cent.C
root -l -b -q fpPb_JE_LKRatio.C
root -l -b -q fpPb_JE_LKRatio_Cent.C
root -l -b -q fpPb_JE_OKRatio.C
root -l -b -q fpPb_JE_OLRatio.C
root -l -b -q fpPb_JE_Omega.C
root -l -b -q fpPb_JE_OXRatio.C
root -l -b -q fpPb_JE_Xi.C
root -l -b -q fpPb_JE_Xi_Cent.C
root -l -b -q fpPb_JE_XKRatio.C
root -l -b -q fpPb_JE_XKRatio_Cent.C
root -l -b -q fpPb_JE_XLRatio.C
root -l -b -q fpPb_JE_XLRatio_Cent.C
root -l -b -q fpPb_UE_Kshort_Cent.C
root -l -b -q fpPb_UE_Lambda_Cent.C
root -l -b -q fpPb_UE_LKRatio_Cent.C
root -l -b -q fpPb_UE_Xi_Cent.C
root -l -b -q fpPb_UE_XKRatio_Cent.C
root -l -b -q fpPb_UE_XLRatio_Cent.C
root -l -b -q fpp_Incl_Kshort.C
root -l -b -q fpp_Incl_Lambda.C
root -l -b -q fpp_Incl_LKRatio.C
root -l -b -q fpp_Incl_OKRatio.C
root -l -b -q fpp_Incl_OLRatio.C
root -l -b -q fpp_Incl_Omega.C
root -l -b -q fpp_Incl_OXRatio.C
root -l -b -q fpp_Incl_Xi.C
root -l -b -q fpp_Incl_XKRatio.C
root -l -b -q fpp_Incl_XLRatio.C
root -l -b -q fpp_JE_Kshort.C
root -l -b -q fpp_JE_Lambda.C
root -l -b -q fpp_JE_LKRatio.C
root -l -b -q fpp_JE_OKRatio.C
root -l -b -q fpp_JE_OLRatio.C
root -l -b -q fpp_JE_Omega.C
root -l -b -q fpp_JE_OXRatio.C
root -l -b -q fpp_JE_Xi.C
root -l -b -q fpp_JE_XKRatio.C
root -l -b -q fpp_JE_XLRatio.C
